openapi: 3.0.1
info:
  title: workshop
  description: ''
  version: '1.0'
servers:
  - url: https://gateway.contosoapi202201.com/workshop
  - url: https://selfgw.contosoapi202201.com/workshop
paths:
  /healthcheck:
    get:
      summary: HealtHcheck
      operationId: healthcheck
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]