openapi: 3.0.1
info:
  title: Myapp2
  description: This is a simple App hosted on top of a ASE environment with a full private dns
  version: '1.0'
servers:
  - url: https://apim-bob-dev-eastus-001.azure-api.net/myapp
paths:
  /api/Values:
    get:
      tags:
        - Values
      summary: /api/Values - GET
      operationId: get-api-values
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  type: string
              examples:
                default:
                  value: 
            application/json:
              schema:
                type: array
                items:
                  type: string
              example:
                - string
            text/json:
              schema:
                type: array
                items:
                  type: string
              example:
                - string
    post:
      tags:
        - Values
      summary: /api/Values - POST
      operationId: post-api-values
      requestBody:
        content:
          application/json:
            schema:
              type: string
            example: string
          text/json:
            schema:
              type: string
            example: string
          application/*+json:
            schema:
              type: string
            example: string
      responses:
        '200':
          description: Success
  '/api/Values/{id}':
    get:
      tags:
        - Values
      summary: '/api/Values/{id} - GET'
      operationId: get-api-values-id
      parameters:
        - name: id
          in: path
          description: Format - int32.
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
              examples:
                default:
                  value: 
            application/json:
              schema:
                type: string
              example: string
            text/json:
              schema:
                type: string
              example: string
    put:
      tags:
        - Values
      summary: '/api/Values/{id} - PUT'
      operationId: put-api-values-id
      parameters:
        - name: id
          in: path
          description: Format - int32.
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              type: string
            example: string
          text/json:
            schema:
              type: string
            example: string
          application/*+json:
            schema:
              type: string
            example: string
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Values
      summary: '/api/Values/{id} - DELETE'
      operationId: delete-api-values-id
      parameters:
        - name: id
          in: path
          description: Format - int32.
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]