apimServiceName: [prod apim instance name goes here]
namedValues:
  - name: environment
    displayName: environment
    value: "https://www.search.com"
  - name: mysecretvalue
    displayName: mysecretvalue
    keyVault:
      identityClientId: [your guid goes here]
      secretIdentifier: [your url here]
  - name: testSecret
    displayName: testSecret
    value: "{#testSecretValue#}"
loggers:
    - name: apim-lab-insights
      loggerType: applicationInsights
      description: prod application insights
      resourceId: "/subscriptions/[your guid here]/resourceGroups/
                   rg-apim-lab-prod/providers/microsoft.insights/components/apim-lab-prod-insights"
      credentials:
        instrumentationKey: "{{Logger-Credentials--62825ade46346113589affc1}}"
        isBuffered: true
diagnostics:
   - name: applicationinsights
     verbosity: Error
     loggerId: "/subscriptions/[subscripotion id]/resourceGroups/rg-apim-lab-prod/providers/Microsoft.ApiManagement/service/apim-prod-wk-05102022/loggers/apim-lab-prod-insights" 
apis:
  - name: demo-conference-api
    diagnostics:
      - name: applicationinsights
        verbosity: Error
        loggerId: "/subscriptions/[subscripotion id]/resourceGroups/rg-apim-lab-prod/providers/Microsoft.ApiManagement/service/apim-prod-wk-05102022/loggers/apim-lab-prod-insights"
  - name: myapi
    serviceUrl: https://mysite.com
backends:
  - name: mybackend
    url: https://myenvironmenturl.com
