# Note: Since the introduction of workspaces we recommend using workspaces instead of using this file to inform apiops about extracting select artifacts instead of extracting everything. 
# We are keeping support for this file as not everyone will be able to use workspaces.
# More information about workspaces can be found here https://learn.microsoft.com/en-us/azure/api-management/workspaces-overview

 apiNames:
  - eshoponcontainers-basket-http-api
  - eshoponcontainers-catalog
  - eshoponcontainers-ordering-api
  - maps-findlocation
  - 64ad5daaff2257c969a8e4b9
  - wsib-enterpriseintegrations-eclearance-internal
  - returnname
  - returnname-v1



#  loggerNames:
#   - loggerName1
#   - loggerName2

#  namedValueNames:
#   - namedValueName1
#   - namedValueName2

#  productNames:
#   - productName2
#   - productName2

#  backendNames:
#   - backend1
#   - backend2

#  tagNames:
#   - tag1
#   - tag2
