openapi: 3.0.1
info:
  title: Myapp-MultiSufix
  description: This is a simple App hosted on top of a ASE environment with a full private dns
  version: '1.0'
servers:
  - url: https://apim-bob-dev-eastus-001.azure-api.net/myapp-clone/suffix
paths:
  '/api/Values/{id}':
    put:
      summary: '/api/Values/{id} - PUT'
      description: '/api/Values/{id} - PUT'
      operationId: 64ad5dbb7f5bffbf0746d5e1
      parameters:
        - name: id
          in: path
          description: Format - int32.
          required: true
          schema:
            type: integer
            format: int32
      requestBody:
        content:
          application/json:
            schema:
              type: string
            example: string
          text/json:
            schema:
              type: string
            example: string
          application/*+json:
            schema:
              type: string
            example: string
      responses:
        '200':
          description: Success
    get:
      summary: '/api/Values/{id} - GET'
      description: '/api/Values/{id} - GET'
      operationId: 64ad5dbb0cba571a2f4b5a24
      parameters:
        - name: id
          in: path
          description: Format - int32.
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: string
              examples:
                default:
                  value: 
            application/json:
              schema:
                type: string
              example: string
            text/json:
              schema:
                type: string
              example: string
    delete:
      summary: '/api/Values/{id} - DELETE'
      description: '/api/Values/{id} - DELETE'
      operationId: 64ad5dbbe8770adf20f31b33
      parameters:
        - name: id
          in: path
          description: Format - int32.
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  /api/Values:
    post:
      summary: /api/Values - POST
      description: /api/Values - POST
      operationId: 64ad5dbb4f06e0c9fe00f229
      requestBody:
        content:
          application/json:
            schema:
              type: string
            example: string
          text/json:
            schema:
              type: string
            example: string
          application/*+json:
            schema:
              type: string
            example: string
      responses:
        '200':
          description: Success
    get:
      summary: /api/Values - GET
      description: /api/Values - GET
      operationId: 64ad5dbbd7e03862a5f3b284
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                type: array
                items:
                  type: string
              examples:
                default:
                  value: 
            application/json:
              schema:
                type: array
                items:
                  type: string
              example:
                - string
            text/json:
              schema:
                type: array
                items:
                  type: string
              example:
                - string
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]