openapi: 3.0.1
info:
  title: apimcallapim
  description: ''
  version: '1.0'
servers:
  - url: https://gateway.contosoapi202201.com/apimcallapim
  - url: https://selfgw.contosoapi202201.com/apimcallapim
paths:
  /invoke:
    post:
      summary: invoke
      operationId: 6320d55735e44680b713bbbd
      parameters:
        - name: api-version
          in: query
          schema:
            enum:
              - ''
            type: ''
        - name: sp
          in: query
          schema:
            enum:
              - ''
            type: ''
        - name: sv
          in: query
          schema:
            enum:
              - ''
            type: ''
        - name: sig
          in: query
          schema:
            enum:
              - ''
            type: ''
      responses:
        '200':
          description: 
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]