openapi: 3.0.1
info:
  title: maps/findlocation
  description: ''
  version: '1.0'
servers:
  - url: https://apim-bob-dev-eastus-001.azure-api.net/maps/findlocation
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]