openapi: 3.0.1
info:
  title: DemoMELCC
  description: ''
  version: '1.0'
servers:
  - url: https://gateway.contosoapi202201.com/environment
  - url: https://selfgw.contosoapi202201.com/environment
paths: { }
components:
  securitySchemes:
    apiKeyHeader:
      type: apiKey
      name: Ocp-Apim-Subscription-Key
      in: header
    apiKeyQuery:
      type: apiKey
      name: subscription-key
      in: query
security:
  - apiKeyHeader: [ ]
  - apiKeyQuery: [ ]